<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

|Term|Brief Description|
|:----|:---:|
|Subsetting|Selecting an object or objects from a list or array|
|Indexing|Selecting a specific object from a list or array using its position in it|
|Slicing|Selecting a range of objects from a list or array using its position in it|
|Masking|Filtering the elements in an array using conditions to return an array corresponding to True or False|

# Exercise 2

In [8]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0]
# .astype() coverts all the elements within the array into the specified type (i.e. int)
integers = numbers.astype(int) 
mask = (integers % 2) != 0
odd_numbers = np_array_2d[mask]
letters = odd_numbers[:, 1]
print(letters)


['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [29]:
array_2d = [[66, 50, 57, -1, -1],
[92, -1, 88, -1, -1],
[75, -1, -1, 76, -1],
[-1, 51, 87, -1, -1],
[71, -1, 67, -1, 69]]

np_array_2d = np.array(array_2d)
mask_1 = np_array_2d < 50
mask_2 = np_array_2d > 50 


final_array = (np_array_2d * 0) - mask_1 + mask_2
print(final_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
