<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

Subsetting means to "select" something from a list or array.

Indexing refers to selecting one element within a list or array.

Slicing refers to selecting a range of elements within a list or arrays.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [7]:
py_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
np_array = np.array(py_list)
x = np_array

print(x[0]) # First Element
print(x[-1]) # Last Element
print(x[0:3]) # First to Third Element
print(x[1:4:2]) # Second to Fourth Element in steps of 2
print(x[5:]) # Sixth Element to Last Element
print(x[:5]) # First to Fifth Element
print(x[4:2:-1]) # Fourth to Third Element (i.e. in reverse)
print(x[::-1]) # Reverse the entire list


0
9
[0 1 2]
[1 3]
[5 6 7 8 9]
[0 1 2 3 4]
[4 3]
[9 8 7 6 5 4 3 2 1 0]


## 1.2 Arrays only | Subsetting by masking

Subsetting by masking is one of the most powerful things that NumPy arrays can do. Masks will always have True or False as elements, and they will have the same structure as the original NumPy array itself. When subsetting by masking, a new NumPy array with the elements that correspond to the True values in the mask will be returned.

In [10]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)
print(np_array[my_mask])

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


In [12]:
print(np_array[~(np_array > 3)]) # ~ means NOT
print(np_array[(np_array < 3) | (np_array > 8)]) # | means OR
print(np_array[(np_array > 3) & (np_array < 8)]) # & means AND

[1 2 3]
[ 1  2  9 10]
[4 5 6 7]


When combining masks, always use Bitwise NOT (~), Bitwise OR (|) and Bitwise AND (&). Always use brackets to separate out the conditions.

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

Another difference between lists and arrays is in the way they index and slice in higher dimensions:

In [6]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"], [5, "E"], [6, "F"], [7, "G"], [8, "H"], [9, "I"], [10, "J"]]
np_array_2d = np.array(py_list_2d)

# The fourth element in the list/array
print(py_list_2d[3]) 
print(np_array_2d[3])

# The first element in the fourth element in the list/array
print(py_list_2d[3][0])
print(np_array_2d[3, 0])

# The first three elements in the list/array
print(py_list_2d[:3])
print(np_array_2d[:3])

# The first element in a list of the first three elements in the list
print(py_list_2d[:3][0])

#The first element in each element of the array consisting of the first three elements in the array
print(np_array_2d[:3, 0])

# The first element in a list of the foruth to sixth element in the list
print(py_list_2d[3:6][0])

# The first element in each element of the array consisting of the fourth to sixth element in the array
print(np_array_2d[3:6, 0])

# The first element in each element in the array
print(np_array_2d[:, 0])

[4, 'D']
['4' 'D']
4
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
[1, 'A']
['1' '2' '3']
[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 1.4 Growing lists

NumPy arrays are great at slicing and also for working with mathematics, but lists are easy to grow and do so very efficiently. NumPy arrays ont the other hand are not so easy to change.

In [8]:
x = [1, 2] * 5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

There are three ways to append elements on at a time to a list: using ```+```, ```+=``` and ```.append()```.

In [9]:
x = [1]
x = x + [2]
x = x + [3]
x

[1, 2, 3]

In [10]:
x = [1] 
x += [2]
x += [3]
x

[1, 2, 3]

In [11]:
x = [1] 
x.append(2)
x.append(3)
x

[1, 2, 3]

```.append()``` runs much faster than the rest of the options.

# Some loose ends

## 1.5 Tuples

Tuples can be marked by ```()``` and they cannot be changed after they are created, hence they are immutable.

In [12]:
a = (1, 2, 3)
print(a[0])

1


Data within tuples can be accessed similar to lists but they cannot be changed.

In [13]:
a[0] = -1

TypeError: 'tuple' object does not support item assignment

In [14]:
a[0] += 1

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

When making copies of lists and arrays, be sure to use ```.copy()``` in order to not affect the original list too.

In [18]:
x = [1, 2, 3]
y = x
z = x
z += [4]
print(f"{x = }, {y = }, and {z = }")

x = [1, 2, 3, 4], y = [1, 2, 3, 4], and z = [1, 2, 3, 4]


In [17]:
x = [1, 2, 3]
y = x.copy()
z = x.copy()
z += [4]
print(f"{x = }, {y = }, and {z = }")


x = [1, 2, 3], y = [1, 2, 3], and z = [1, 2, 3, 4]


## Footnotes